services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: alamakota
      POSTGRES_USER: board_games
      POSTGRES_DB: games
    ports:
      - 5432:5432

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PORT: 5432
      POSTGRES_DB: games
      POSTGRES_USER: board_games
      POSTGRES_PASSWORD: alamakota
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      JWT_KEY: dev-secret
    ports:
      - 8080:8080
    depends_on:
      - postgres
