apiVersion: v1
kind: Service
metadata:
  name: {{ include "wuda-app.fullname" . }}-backend
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "wuda-app.labels" . | nindent 4 }}
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.backend.port | default 8080 }}
    targetPort: {{ .Values.backend.port | default 8080 }}
    protocol: TCP
  selector:
    {{- include "wuda-app.selectorLabels" . | nindent 4 }}
    component: backend


