apiVersion: v1
kind: Service
metadata:
  name: {{ include "wuda-app.fullname" . }}-frontend
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "wuda-app.labels" . | nindent 4 }}
    component: frontend
spec:
  type: NodePort
  ports:
  - port: {{ .Values.frontend.port | default 8000 }}
    targetPort: {{ .Values.frontend.port | default 8000 }}
    protocol: TCP
    nodePort: {{ .Values.frontend.nodePort | default 30080 }}
  selector:
    {{- include "wuda-app.selectorLabels" . | nindent 4 }}
    component: frontend


