apiVersion: v1
kind: Service
metadata:
  name: {{ include "wuda-app.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "wuda-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: postgres

spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "wuda-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: postgres
