apiVersion: v1
kind: Service
metadata:
  name: {{ include "wuda-app.fullname" . }}-postgres
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "wuda-app.labels" . | nindent 4 }}
    component: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    {{- include "wuda-app.selectorLabels" . | nindent 4 }}
    component: postgres


