name: backend-ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # TODO: Lintują kod, szukają podatności w kodzie

      # Pobranie kodu z repozytorium
      - name: Checkout repo
        uses: actions/checkout@v4

      # Budowanie obrazu backendu z folderu /back-end

      # budują obrazy dockerowe (tak), przeprowadzają testy jednostkowe aplikacji (tak)
      # tu trzeba dopasować sleep (na razie jest git)
      - name: Build and start services
        run: |
          docker compose up -d --build backend postgres
          echo "Czekam aż backend i baza wystartują..."
          sleep 15

      - name: Unit tests inside container
        run: docker compose run --rm backend pytest -ra

      #sprawdza echa czy wszytko stoi
      # Mechanizm sprawdzający czy otrzymane wiaodmośći są poprawne (odpowiada za ot flaga -f)
      - name: Test liveness/readiness endpoints
        run: |
          echo "Testuję endpoint /liveness"
          curl -f http://localhost:8080/liveness
          echo "Testuję endpoint /readiness"
          curl -f http://localhost:8080/readiness

      # Jeżeli testy zostaną wykonane pomyślnie to potok wrzuca obrazy dockerowe do rejestru githubowego (może też być dockerhub).

      - name: Log in to GitHub Container Registry
        if: ${{ success() }}
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Push backend image to GHCR
        if: ${{ success() }}
        run: |
          IMAGE_BASE="ghcr.io/${{ secrets.GHCR_USERNAME }}/backend"
          GIT_SHA="${{ github.sha }}"
          docker tag backend:latest "${IMAGE_BASE}:latest"
          docker tag backend:latest "${IMAGE_BASE}:${GIT_SHA}"
          docker push "${IMAGE_BASE}:latest"
          docker push "${IMAGE_BASE}:${GIT_SHA}"

      # sprzątanie
      - name: Stop and clean up
        if: always()
        run: docker compose down -v
