name: backend-ci

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # TODO: Lintują kod, szukają podatności w kodzie

      # Pobranie kodu z repozytorium
      - name: Checkout repo
        uses: actions/checkout@v4

      # Budowanie obrazu backendu z folderu /back-end
      # Testy są w Dockerfile, uruchomią się automatycznie w tym kroku
      - name: Build and start services
        run: |
          docker compose -f docker-compose.yaml up -d --build
          echo "Czekam aż backend i baza wystartują..."
          sleep 15
        # tu trzeba dopasować

        #sprawdza echa czy wszytko stoi
      - name: Test liveness/readiness endpoints
        run: |
          echo "Testuję endpoint /liveness"
          curl -f http://localhost:8080/liveness
          echo "Testuję endpoint /readiness"
          curl -f http://localhost:8080/readiness

      # TODO: budują obrazy dockerowe (tak), przeprowadzają testy jednostkowe aplikacji (?)
      # Przenieść testy z Docerfile tutaj?

      # TODO: jeżeli testy zostaną wykonane pomyślnie to potok wrzuca obrazy dockerowe do rejestru githubowego (może też być dockerhub).

      # sprzątanie
      - name: Stop and clean up
        if: always()
        run: docker compose down -v
