name: frontend-ci

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [master]
    paths:
      - "front-end/**"
  pull_request:
    paths:
      - "front-end/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Pobranie kodu z repozytorium
      - name: Checkout repo
        uses: actions/checkout@v4

      # Analiza jakości i bezpieczeństwa kodu
      - name: Install lint & security tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit pip-audit

      # w kolejności co robi co:
      # liczba błędów na końcu
      # ignorowanie błędów zbyt długich linii (>79 znaków)
      # maksymalna złożoność funkcji to 10
      # dozwolona długość linii to 120 znaków
      # pokazuje się fragment kodu, w którym jest błąd
      # na końcu wyświetlane statystyki błędów
      - name: Lint code with Flake8
        run: |
          echo "Sprawdzam styl i błędy składniowe we froncie..."
          cd front-end
          flake8 . --count --ignore=E501 --max-complexity=10 --max-line-length=120 --show-source --statistics || true

      # bandit analizuje rekurencyjnie (-r .) a -lll pokazuje tylko błędy o najwyższym poziomie ryzyka
      - name: Run security checks with Bandit
        run: |
          echo "Analizuję kod pod kątem podatności..."
          cd front-end
          bandit -r . -lll

      # -r ma za zadanie czytania pliku z listą zależności
      # || true pozwala przejść dalej nawet, jeśli pip-audit znajdzie błędy ( czyli prościej -> nie przerywa pipeline’u)
      - name: Check dependencies vulnerabilities with pip-audit
        run: |
          echo "Sprawdzam zależności z requirements.txt..."
          pip-audit -r back-end/requirements.txt || true

      # Budowanie obrazu backendu z folderu /front-end
      - name: Build and start services
        run: |
          docker compose up -d --build frontend
          echo "Czekam aż backend i baza wystartują..."
          sleep 15

      # Testy jednostkowe frontendu
      - name: Run frontend unit tests
        run: |
          docker compose run --rm frontend pytest -ra

      # Sprawdza czy frontend odpowiada (czy serwer po prostu odpowiada na porcie 8000)
      - name: Test frontend endpoint
        run: |
          echo "Testuję endpoint frontendu"
          curl -f http://localhost:8000 || exit 1

      - name: Log in to GitHub Container Registry
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Push obrazu z wersjonowaniem i zachowaniem historii
      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/frontend
          TAG=${{ github.sha }}
          docker tag frontend:latest $IMAGE_NAME:latest
          docker tag frontend:latest $IMAGE_NAME:$TAG
          echo "Pushing image to GitHub Container Registry..."
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG

      # kontenery nie są usuwane, tylko zatrzymane
      - name: Stop containers
        if: always()
        run: docker compose stop
